In [1]:
import pandas as pd

In [2]:
import numpy as np

## Series is 1D & DataFrames are 2D Objects

### 1. But Why?

### 2. And What exactly is index?

In [4]:
# can we have multiple index? Let's try

In [5]:
index_val = [('cse', 2019), ('cse', 2020), ('cse', 2021), ('cse', 2022), ('ece', 2019), ('ece', 2020), ('ece', 2021), ('ece', 2022)]

In [12]:
a = pd.Series([1,2,3,4,5,6,7,8], index = index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [8]:
#The problem?

In [11]:
a['cse']

KeyError: 'cse'

In [13]:
#The solution -> multiindex series(also Known as Hierarchical Indexing)
#Multiple index levels within a single index

In [14]:
#How to create multiindex object
# 1. pd.MultiIndex.from_tuples()
# 2. pd.MultiIndex.from_product()

In [17]:
index_val = [('cse', 2019), ('cse', 2020), ('cse', 2021), ('cse', 2022), ('ece', 2019), ('ece', 2020), ('ece', 2021), ('ece', 2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)

In [19]:
multiindex #Its is called multi index object

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [20]:
pd.MultiIndex.from_product([['cse','ece'],[2019, 2020, 2021, 2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [21]:
#level inside multiindex object

In [22]:
multiindex.levels[1]

Index([2019, 2020, 2021, 2022], dtype='int64')

In [23]:
# Creating series with Multiindex object

In [26]:
s = pd.Series([1,2,3,4,5,6,7,8], index = multiindex)

In [27]:
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [28]:
# How to fetch items from such a series

In [29]:
s['cse', 2022]

np.int64(4)

In [30]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [31]:
#unstack

In [32]:
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [38]:
temp = s.unstack()

In [39]:
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [34]:
#stack

In [35]:
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [40]:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [41]:
#melt -> simple example branch

In [42]:
# wide to long

In [43]:
pd.DataFrame({'cse':[120]})

   cse
0  120

In [44]:
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [45]:
pd.DataFrame({'cse':[120], 'ece':[100], 'mech':[50]})

   cse  ece  mech
0  120  100    50

In [48]:
pd.DataFrame({'cse':[120], 'ece':[100], 'mech':[50]}).melt(var_name='branch', value_name = 'num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech            50